name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy
        uses: dnwe/setup-trivy@b557cafadcebc1d7433d78929173b5271ee9f3c9
        with:
          version: v0.60.0

      - name: Test trivy run
        shell: bash
        run: trivy -v
